### ISSUE TITLE
Couldn't set it up

### ISSUE THREAD

**Issue by rafaellupo** [nikolaynesov/vue-body-class#5] opened 2017-11-06 19:42 UTC
Hi, I have followed the steps and the body class never changes. Can you see something I'm doing wrong? Regards!
```js
//router.map.js
import App from './components/App.vue'
import Form from './components/produto/Form.vue'
import Blank from './components/Blank.vue'
import Login from './components/auth/Login.vue'

const stdBodyClass = 'hold-transition skin-blue sidebar-mini'
const loginBodyClass = 'hold-transition login-page'

export default [
    {
        name: 'app',
        path: '/',
        component: App,
        meta: {
            bodyClass: stdBodyClass
        },
        children: [
            {
                name: 'produto_table.list',
                path: '/produtos',
                component: Form
            },
            {
                name: 'app.blank',
                path: '/',
                component: Blank
            }
        ]
    },
    {
        name: 'login',
        path: '/login',
        component: Login,
        meta: {
            bodyClass: loginBodyClass
        }
    }
]
```

```js
//router.js
import VueRouter from 'vue-router'
import routes from './router.map'


export const router = new VueRouter({
    routes
})
```

```js
//app.js
import Vue from 'vue'
import VueRouter from 'vue-router'
import store from './store/store'
import { router } from './router'
import AppComponent from './components/App.vue'
import vbclass from 'vue-body-class'


Vue.use(vbclass, VueRouter)

const appVue = new Vue({
    el: '#app',
    store,
    router,
    components: {
        'app': AppComponent
    }
});

```

**Comment by nikolaynesov** [comment] 2017-11-07 01:16
@rafaellupo please, follow the installation steps. 
It says:

> After the router instance was created with all the routes, use it with Vue.use global method to explicitly install the plugin.

So you need to use:
`Vue.use(vbclass, router)`

It also relates to 
https://github.com/nikolaynesov/vue-body-class/issues/4

I am closing the issue, but if the problem is still there, please feel free to report in the thread.

**Closed by nikolaynesov** 2017-11-07 01:16 UTC
